# Generated by Django 5.2.8 on 2025-12-13 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_rubric_alter_bb_options_alter_bb_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BbExtra',
            fields=[
                ('bb', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bboard.bb', verbose_name='Объявление')),
                ('is_broken', models.BooleanField(default=False, verbose_name='Требует ремонта?')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email для связи')),
            ],
            options={
                'verbose_name': 'Дополнительно',
                'verbose_name_plural': 'Дополнительные параметры',
            },
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Стикер')),
            ],
            options={
                'verbose_name': 'Стикер',
                'verbose_name_plural': 'Стикеры',
            },
        ),
        migrations.AddField(
            model_name='bb',
            name='stickers',
            field=models.ManyToManyField(blank=True, to='bboard.sticker', verbose_name='Стикеры'),
        ),
    ]
