# Generated by Django 5.2.8 on 2025-12-13 22:36

import bboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_bbextra_sticker_bb_stickers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='price',
            field=models.FloatField(validators=[bboard.models.validate_non_negative], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='title',
            field=models.CharField(max_length=50, validators=[bboard.models.validate_clean_title, bboard.models.validate_capital_start], verbose_name='Товар'),
        ),
    ]
