# Generated by Django 5.2.8 on 2025-12-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_alter_bb_price_alter_bb_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bbs/', verbose_name='Фото'),
        ),
    ]
