# Generated by Django 5.2.8 on 2025-12-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0005_bb_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='Город'),
        ),
    ]
