# Generated by Django 5.2.8 on 2025-12-23 20:15

import bboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0006_bb_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='title',
            field=models.CharField(max_length=100, validators=[bboard.models.validate_clean_title, bboard.models.validate_capital_start], verbose_name='Товар'),
        ),
    ]
