# Generated by Django 5.2.8 on 2025-12-23 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0008_bb_is_active'),
    ]

    operations = [
    ]
